spring:
  application:
    name: app1
  kafka:
    listener:
      ack-mode: record
    bootstrap-servers: localhost:9092
    consumer:
      group-id: app1-study-kafka
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
#      properties:
#        interceptor.classes: com.kafka.app1.configs.LoggingProducerInterceptor
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      retries: 2
#      delivery-timeout-ms: 30000
#      enable-idempotence: true
#      transaction-id-prefix: tx-

springdoc:
  swagger-ui:
    path: /api
  api-docs:
    path: /v3/api-docs

server:
  port: 8888

